import { SaleListItem, SalesSummaryData } from "./sales.types";

export const mockPopulatedSales: SaleListItem[] = [
  {
    id: "sale-024",
    reference: "VTE-0024",
    occurredAt: "17/08/2026 14:32",
    customer: { name: "Client comptoir" },
    itemCount: 2,
    totalAmount: 25000,
    paidAmount: 25000,
    remainingAmount: 0,
    paymentMethod: "cash",
    paymentStatus: "Payée",
    saleStatus: "Terminée",
    seller: { id: "user-1", name: "Hamidou" },
  },
  {
    id: "sale-023",
    reference: "VTE-0023",
    occurredAt: "17/08/2026 12:15",
    customer: { id: "cust-1", name: "Awa Traoré" },
    itemCount: 4,
    totalAmount: 75000,
    paidAmount: 50000,
    remainingAmount: 25000,
    paymentMethod: "wave",
    paymentStatus: "Partiellement payée",
    saleStatus: "Terminée",
    seller: { id: "user-1", name: "Hamidou" },
  },
  {
    id: "sale-022",
    reference: "VTE-0022",
    occurredAt: "17/08/2026 10:40",
    customer: { id: "cust-2", name: "Moussa Diallo" },
    itemCount: 3,
    totalAmount: 35000,
    paidAmount: 0,
    remainingAmount: 35000,
    paymentMethod: "credit",
    paymentStatus: "À encaisser",
    saleStatus: "Terminée",
    seller: { id: "user-1", name: "Hamidou" },
  },
  {
    id: "sale-021",
    reference: "VTE-0021",
    occurredAt: "17/08/2026 09:15",
    customer: { id: "cust-3", name: "Boulangerie Modibo" },
    itemCount: 8,
    totalAmount: 190000,
    paidAmount: 190000,
    remainingAmount: 0,
    paymentMethod: "bank_transfer",
    paymentStatus: "Payée",
    saleStatus: "Terminée",
    seller: { id: "user-1", name: "Hamidou" },
  },
  {
    id: "sale-020",
    reference: "VTE-0020",
    occurredAt: "16/08/2026 17:50",
    customer: { id: "cust-4", name: "Oumou Coulibaly" },
    itemCount: 5,
    totalAmount: 100000,
    paidAmount: 0,
    remainingAmount: 100000,
    paymentMethod: "credit",
    paymentStatus: "À encaisser",
    saleStatus: "Terminée",
    seller: { id: "user-2", name: "Aminata" },
  },
  {
    id: "sale-019",
    reference: "VTE-0019",
    occurredAt: "16/08/2026 15:20",
    customer: { id: "cust-5", name: "Ibrahim Sangaré" },
    itemCount: 2,
    totalAmount: 45000,
    paidAmount: 45000,
    remainingAmount: 0,
    paymentMethod: "orange_money",
    paymentStatus: "Remboursée",
    saleStatus: "Remboursée",
    seller: { id: "user-1", name: "Hamidou" },
  },
  {
    id: "sale-018",
    reference: "VTE-0018",
    occurredAt: "16/08/2026 11:05",
    customer: { id: "cust-6", name: "Boutique Fatou" },
    itemCount: 6,
    totalAmount: 60000,
    paidAmount: 30000,
    remainingAmount: 30000,
    paymentMethod: "mixed",
    paymentStatus: "Partiellement payée",
    saleStatus: "Terminée",
    seller: { id: "user-2", name: "Aminata" },
  },
  {
    id: "sale-017",
    reference: "VTE-0017",
    occurredAt: "15/08/2026 18:00",
    customer: { id: "cust-7", name: "Seydou Keita" },
    itemCount: 1,
    totalAmount: 15000,
    paidAmount: 0,
    remainingAmount: 0, // Cancelled sale MUST NOT expose remaining collectible balance
    paymentMethod: "cash",
    paymentStatus: "Remboursée",
    saleStatus: "Annulée",
    seller: { id: "user-1", name: "Hamidou" },
  },
  {
    id: "sale-016",
    reference: "VTE-0016",
    occurredAt: "15/08/2026 14:10",
    customer: { name: "Client comptoir" },
    itemCount: 3,
    totalAmount: 85000,
    paidAmount: 85000,
    remainingAmount: 0,
    paymentMethod: "card",
    paymentStatus: "Payée",
    saleStatus: "Terminée",
    seller: { id: "user-1", name: "Hamidou" },
  },
  {
    id: "sale-015",
    reference: "VTE-0015",
    occurredAt: "15/08/2026 10:30",
    customer: { id: "cust-8", name: "Kadiatou Touré" },
    itemCount: 4,
    totalAmount: 120000,
    paidAmount: 120000,
    remainingAmount: 0,
    paymentMethod: "orange_money",
    paymentStatus: "Payée",
    saleStatus: "Terminée",
    seller: { id: "user-2", name: "Aminata" },
  },
  {
    id: "sale-014",
    reference: "VTE-0014",
    occurredAt: "14/08/2026 16:45",
    customer: { id: "cust-9", name: "Alassane Bah" },
    itemCount: 7,
    totalAmount: 210000,
    paidAmount: 150000,
    remainingAmount: 60000,
    paymentMethod: "mixed",
    paymentStatus: "Partiellement payée",
    saleStatus: "Terminée",
    seller: { id: "user-1", name: "Hamidou" },
  },
  {
    id: "sale-013",
    reference: "VTE-0013",
    occurredAt: "14/08/2026 09:00",
    customer: { name: "Client comptoir" },
    itemCount: 12,
    totalAmount: 465000,
    paidAmount: 355000,
    remainingAmount: 110000,
    paymentMethod: "wave",
    paymentStatus: "Partiellement payée",
    saleStatus: "Terminée",
    seller: { id: "user-1", name: "Hamidou" },
  },
];

/**
 * Period summary snapshot representing global aggregated business metrics
 * across the selected accounting period (e.g. 24 total sales).
 */
export const mockSummaryData: SalesSummaryData = {
  totalSalesCount: 24,
  totalSalesAmount: 1425000,
  totalCollectedAmount: 1050000,
  totalToCollectAmount: 375000,
};
