import { DashboardSnapshot } from "./dashboard.types";
import { formatMoney } from "./dashboard.utils";

export const mockPopulatedSnapshot: DashboardSnapshot = {
  userFirstName: "Hamidou",
  businessName: "Diallo Commerce",
  periodLabel: "Aujourd’hui",
  hasBusinessActivity: true,
  metrics: {
    todaySales: {
      id: "metric-today-sales",
      label: "VENTES AUJOURD’HUI",
      formattedValue: formatMoney(425000),
      rawValue: 425000,
      trend: {
        value: "+12,5 %",
        direction: "up",
        periodContext: "vs hier",
      },
    },
    salesCount: {
      id: "metric-sales-count",
      label: "NOMBRE DE VENTES",
      formattedValue: "24 ventes",
      rawValue: 24,
      unit: "ventes",
      trend: {
        value: "+3",
        direction: "up",
        periodContext: "vs hier",
      },
    },
    toCollect: {
      id: "metric-to-collect",
      label: "À ENCAISSER",
      formattedValue: formatMoney(175000),
      rawValue: 175000,
      subtitle: "4 ventes en attente",
      helperText: "Montant restant à recevoir",
    },
    lowStock: {
      id: "metric-low-stock",
      label: "STOCK À SURVEILLER",
      formattedValue: "6 produits",
      rawValue: 6,
      unit: "produits",
      subtitle: "Niveau critique",
      helperText: "Nécessitent votre attention",
    },
  },
  salesTrend: {
    points: [
      { dayLabel: "Lun", dateStr: "11 Août", amount: 180000 },
      { dayLabel: "Mar", dateStr: "12 Août", amount: 240000 },
      { dayLabel: "Mer", dateStr: "13 Août", amount: 210000 },
      { dayLabel: "Jeu", dateStr: "14 Août", amount: 315000 },
      { dayLabel: "Ven", dateStr: "15 Août", amount: 290000 },
      { dayLabel: "Sam", dateStr: "16 Août", amount: 410000 },
      { dayLabel: "Dim", dateStr: "17 Août", amount: 425000 },
    ],
    percentageChange: 12.5,
    summaryText:
      "Les ventes sont en hausse de 12,5 % sur les 7 derniers jours, atteignant 425 000 FCFA aujourd'hui.",
  },
  attentionItems: [
    {
      id: "att-01",
      category: "payment",
      severity: "warning",
      title: "4 ventes à encaisser",
      description: "175 000 FCFA restent à recevoir sur les ventes en cours.",
      actionLabel: "Voir les ventes",
      actionHref: "/ventes",
    },
    {
      id: "att-02",
      category: "inventory",
      severity: "warning",
      title: "6 produits en stock faible",
      description: "Vérifiez vos niveaux de stock pour éviter les ruptures.",
      actionLabel: "Voir le stock",
      actionHref: "/stocks",
    },
    {
      id: "att-03",
      category: "invoice",
      severity: "danger",
      title: "2 factures en retard",
      description: "Factures échues dépassant le délai de règlement.",
      actionLabel: "Voir les factures",
      actionHref: "/factures",
    },
  ],
  recentSales: [
    {
      id: "sale-01",
      reference: "VTE-0024",
      customerName: "Client comptoir",
      totalAmount: 25000,
      paidAmount: 25000,
      remainingAmount: 0,
      paymentStatus: "Payée",
      saleStatus: "Terminée",
      timestamp: "14:32",
    },
    {
      id: "sale-02",
      reference: "VTE-0023",
      customerName: "Awa Traoré",
      totalAmount: 75000,
      paidAmount: 50000,
      remainingAmount: 25000,
      paymentStatus: "Partiellement payée",
      saleStatus: "Terminée",
      timestamp: "12:15",
    },
    {
      id: "sale-03",
      reference: "VTE-0022",
      customerName: "Moussa Diallo",
      totalAmount: 35000,
      paidAmount: 0,
      remainingAmount: 35000,
      paymentStatus: "À encaisser",
      saleStatus: "Terminée",
      timestamp: "10:40",
    },
    {
      id: "sale-04",
      reference: "VTE-0021",
      customerName: "Boulangerie Modibo",
      totalAmount: 190000,
      paidAmount: 190000,
      remainingAmount: 0,
      paymentStatus: "Payée",
      saleStatus: "Terminée",
      timestamp: "09:15",
    },
    {
      id: "sale-05",
      reference: "VTE-0020",
      customerName: "Oumou Coulibaly",
      totalAmount: 100000,
      paidAmount: 0,
      remainingAmount: 100000,
      paymentStatus: "À encaisser",
      saleStatus: "Terminée",
      timestamp: "Hier 17:50",
    },
  ],
  quickActions: [
    {
      id: "qa-01",
      label: "Nouvelle vente",
      href: "/ventes",
      iconName: "plus-circle",
      description: "Enregistrer un encaissement direct",
    },
    {
      id: "qa-02",
      label: "Ajouter un produit",
      href: "/produits",
      iconName: "package-plus",
      description: "Ajouter un nouvel article au catalogue",
    },
    {
      id: "qa-03",
      label: "Créer une facture",
      href: "/factures",
      iconName: "file-text",
      description: "Émettre une facture ou un devis client",
    },
    {
      id: "qa-04",
      label: "Ajouter une dépense",
      href: "/menu",
      iconName: "wallet-cards",
      description: "Enregistrer des frais de gestion",
    },
  ],
};

export const mockEmptySnapshot: DashboardSnapshot = {
  userFirstName: "Hamidou",
  businessName: "Diallo Commerce",
  periodLabel: "Aujourd’hui",
  hasBusinessActivity: false,
  metrics: {
    todaySales: {
      id: "metric-today-sales",
      label: "VENTES AUJOURD’HUI",
      formattedValue: formatMoney(0),
      rawValue: 0,
    },
    salesCount: {
      id: "metric-sales-count",
      label: "NOMBRE DE VENTES",
      formattedValue: "0 vente",
      rawValue: 0,
    },
    toCollect: {
      id: "metric-to-collect",
      label: "À ENCAISSER",
      formattedValue: formatMoney(0),
      rawValue: 0,
    },
    lowStock: {
      id: "metric-low-stock",
      label: "STOCK À SURVEILLER",
      formattedValue: "0 produit",
      rawValue: 0,
    },
  },
  salesTrend: {
    points: [],
    percentageChange: 0,
    summaryText: "Aucune vente enregistrée pour le moment.",
  },
  attentionItems: [],
  recentSales: [],
  quickActions: mockPopulatedSnapshot.quickActions,
};
